# fly.toml app configuration file generated for moldymoldyguy on 2023-07-21T13:42:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "moldymoldyguy"
primary_region = "ord"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["docker.io/paketobuildpacks/go"]
  [build.args]
    BP_GO_BUILD_FLAGS = "-tags=fts5"
    BP_KEEP_FILES = "html/*:data/*:lieu.toml"

[env]
  PORT = "10001"

[http_service]
  internal_port = 10001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1 
  processes = ["app"]
